[package]
name = "pallet-layerzero-forwarder"
authors = { workspace = true }
description = "A pallet to manage and forward messages comming from layerzero."
edition = "2021"
license = "GPL-3.0-only"
version = "0.1.0"

[package.metadata.docs.rs]
targets = [ "x86_64-unknown-linux-gnu" ]

[lints]
workspace = true

[dependencies]
log = { workspace = true }
parity-scale-codec = { workspace = true }
rand = { workspace = true, optional = true }
scale-info = { workspace = true, features = [ "derive" ] }

frame-support = { workspace = true }
frame-system = { workspace = true }
sp-runtime = { workspace = true }
tp-traits = { workspace = true }
tp-bridge = { workspace = true }

xcm = { workspace = true }
xcm-executor = { workspace = true }
snowbridge-inbound-queue-primitives = { workspace = true }

frame-benchmarking = { workspace = true }

pallet-balances = { workspace = true, optional = true }
pallet-session = { workspace = true, features = [ "historical" ] }
pallet-xcm = { workspace = true }

[dev-dependencies]
pallet-timestamp = { workspace = true }
sp-core = { workspace = true }
sp-io = { workspace = true }

[features]
default = [ "std" ]
std = [
	"frame-benchmarking/std",
	"frame-support/std",
	"frame-system/std",
	"log/std",
	"pallet-balances/std",
	"pallet-session/std",
	"pallet-timestamp/std",
	"parity-scale-codec/std",
	"rand?/std",
	"scale-info/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"tp-traits/std",
	"tp-bridge/std",
	"xcm/std",
	"xcm-executor/std",
	"pallet-xcm/std",
	"snowbridge-inbound-queue-primitives/std",
]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
	"rand",
	"sp-runtime/runtime-benchmarks",
	"tp-traits/runtime-benchmarks",
	"tp-bridge/runtime-benchmarks",
	"xcm/runtime-benchmarks",
	"xcm-executor/runtime-benchmarks",
	"pallet-xcm/runtime-benchmarks",
	"snowbridge-inbound-queue-primitives/runtime-benchmarks",
]

try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-balances?/try-runtime",
	"pallet-session/try-runtime",
	"pallet-timestamp/try-runtime",
	"sp-runtime/try-runtime",
	"pallet-xcm/try-runtime",
]
