keys = [
    "workspace",
    "name",
    "package",
    "bin",
    "lib",
    "test",
    "lints",
    "dependencies",
    "dev-dependencies",
    "build-dependencies",
    "features",
    "default",
    "std",
]

inline_keys = [
    "package",
    "workspace",
    "path",
    "git",
    "branch",
    "rev",
    "version",
    "default-features",
    "optional",
    "features",
]

sort_arrays = true

excludes = [
	"test/configs/zombie_tanssi_relay_k8s_delay.toml"
]
