[package]
authors = ['Steve Degosserie <steve@parity.io>']
description = 'A simple faucet pallet for Substrate-based PoA chains.'
edition = '2018'
homepage = 'https://substrate.dev'
license = 'APACHE-2.0'
name = 'pallet-faucet'
readme = 'README.md'
repository = 'https://github.com/stiiifff/pallet-faucet'
version = '1.0.3'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
parity-scale-codec = { version = "3.2.2", default-features = false, features = [
	"derive",
] }
frame-benchmarking = { workspace = true, optional = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }
scale-info = { workspace = true }

[dev-dependencies]
sp-core = { workspace = true }
sp-io = { workspace = true }
serde = { version = '1.0.100', default-features = false, features = ['derive'] }
pallet-balances = { workspace = true, default-features = false }
# pallet-balances = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v1.0.0" }


[features]
default = ['std']
runtime-benchmarks = [
    'frame-benchmarking'
]
std = [
    'parity-scale-codec/std',
    'frame-support/std',
    'frame-system/std',
    'scale-info/std',
    'sp-runtime/std',
    'sp-std/std',
]
try-runtime = [
    'frame-support/try-runtime',
]






