[package]
name = "tp-core"
authors = []
edition = "2021"
license = "GPL-3.0-only"
version = "0.1.1"

[package.metadata.docs.rs]
targets = [ "x86_64-unknown-linux-gnu" ]

[dependencies]
hex-literal = { workspace = true }

# Substrate
parity-scale-codec = { workspace = true }
sp-core = { workspace = true }

# Cumulus
cumulus-primitives-core = { workspace = true, optional = true }

[features]
default = [ "std" ]
std = [
	"parity-scale-codec/std",
	"sp-core/std",
	"cumulus-primitives-core/std",
]