[package]
name = "pallet-registrar-runtime-api"
authors = []
description = "Runtime API definition of pallet-registrar"
edition = "2021"
version = "0.1.0"

[package.metadata.docs.rs]
targets = [ "x86_64-unknown-linux-gnu" ]
[dependencies]
pallet-registrar = { workspace = true }
parity-scale-codec = { workspace = true, default-features = false }
scale-info = { workspace = true, default-features = false }
sp-api = { workspace = true, default-features = false }
tp-container-chain-genesis-data = { workspace = true }

[features]
default = [ "std" ]
std = [
	"tp-container-chain-genesis-data/std",
	"parity-scale-codec/std",
	"sp-api/std",
]
