[package]
name = "starlight-emulated-chain"
description = "Starlight emulated chain"
edition = "2021"
license = "GPL-3.0-only"
publish = false
version = "0.0.0"
[package.authors]
workspace = true

[lints]
workspace = true

[dependencies]
emulated-integration-tests-common = { workspace = true }
polkadot-parachain-primitives = { workspace = true }
runtime-parachains = { workspace = true }
sp-core = { workspace = true }
starlight-runtime = { workspace = true }
starlight-runtime-constants = { workspace = true }
tanssi-emulated-integration-tests-common = { workspace = true }
xcm = { workspace = true }
xcm-emulator = { workspace = true }
